In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
from sklearn.datasets import load_iris

data = load_iris()

X = data.data
y = data.target

In [5]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [32]:
y = np.where(y == 1 ,1, -1)

In [36]:
y

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [33]:
class Perceptron(object):
    '''
    parameters:
    eta: float between 0 1 
    n_iter : 
    integer
    
    Attributes:
    w_ : 1d-array weights after fitting
    errors_: list. number of misclassication in each epoch
    '''
    
    def __init__(self, eta = 0.01, n_iter = 10):
        self.eta = eta
        self.n_iter = n_iter
        
    def fit(self,X,y):
        self.w_ = np.zeros(1 + X.shape[1]) # it will create array of 1+ n variable in 1d
        self.errors_ = []
        
        for _ in range(self.n_iter):
            errors = 0
            try:
                print(f'iteration_{_} :: {self.w_}')
            except:
                print('starting ...')
                
            for xi, target in zip(X,y):
                print(xi)
                print('---')
                update = self.eta * (target - self.predict(xi))
                self.w_[1:] += update * xi
                self.w_[0] += update
                errors += int(update != 0.0)
            self.errors_.append(errors)
        print('...finished')      
        return self
    
    def net_input(self, X):
        return np.dot(X, self.w_[1:]) + self.w_[0]
    
    def predict(self, X):
        return np.where(self.net_input(X) >= 0.0, 1, -1)
    

In [54]:
model = Perceptron(eta = 0.1, n_iter = 10).fit(X,y)

iteration_0 :: [0. 0. 0. 0. 0.]
[5.1 3.5 1.4 0.2]
---
[4.9 3.  1.4 0.2]
---
[4.7 3.2 1.3 0.2]
---
[4.6 3.1 1.5 0.2]
---
[5.  3.6 1.4 0.2]
---
[5.4 3.9 1.7 0.4]
---
[4.6 3.4 1.4 0.3]
---
[5.  3.4 1.5 0.2]
---
[4.4 2.9 1.4 0.2]
---
[4.9 3.1 1.5 0.1]
---
[5.4 3.7 1.5 0.2]
---
[4.8 3.4 1.6 0.2]
---
[4.8 3.  1.4 0.1]
---
[4.3 3.  1.1 0.1]
---
[5.8 4.  1.2 0.2]
---
[5.7 4.4 1.5 0.4]
---
[5.4 3.9 1.3 0.4]
---
[5.1 3.5 1.4 0.3]
---
[5.7 3.8 1.7 0.3]
---
[5.1 3.8 1.5 0.3]
---
[5.4 3.4 1.7 0.2]
---
[5.1 3.7 1.5 0.4]
---
[4.6 3.6 1.  0.2]
---
[5.1 3.3 1.7 0.5]
---
[4.8 3.4 1.9 0.2]
---
[5.  3.  1.6 0.2]
---
[5.  3.4 1.6 0.4]
---
[5.2 3.5 1.5 0.2]
---
[5.2 3.4 1.4 0.2]
---
[4.7 3.2 1.6 0.2]
---
[4.8 3.1 1.6 0.2]
---
[5.4 3.4 1.5 0.4]
---
[5.2 4.1 1.5 0.1]
---
[5.5 4.2 1.4 0.2]
---
[4.9 3.1 1.5 0.2]
---
[5.  3.2 1.2 0.2]
---
[5.5 3.5 1.3 0.2]
---
[4.9 3.6 1.4 0.1]
---
[4.4 3.  1.3 0.2]
---
[5.1 3.4 1.5 0.2]
---
[5.  3.5 1.3 0.3]
---
[4.5 2.3 1.3 0.3]
---
[4.4 3.2 1.3 0.2]
---
[5.  3.5 1.6 0.6]
---


In [55]:
model.predict(X)

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

In [56]:
from sklearn.metrics import accuracy_score

In [57]:
acc = accuracy_score(y,model.predict(X))
print('{:.3}%'.format(acc*100))

66.7%


In [58]:
y

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])